### ISSUE TITLE
Page title setting does not work for "same view class different routes" 

### ISSUE THREAD

**Issue by alex-kowalczyk** [vinicius73/vue-page-title#8]
The mixin does not cover a scenario when we switch from one route to another, but with the same view class handling the route. 

Hooking into `updated()` would fix that. 
It would also allow for setting reactive page titles.

**Comment by vinicius73** [comment]
Can you provide a demo about this issue?

**Comment by alex-kowalczyk** [comment]
@vinicius73  here is the repo demonstrating the issue.
https://github.com/alex-kowalczyk/vtp-issue

There are two different routes to same view component.
Navigate between the links and observe that page title is not updated - it's frozen to what was set on first page load.

Uncomment mixin code in src/main.js to see the solution proposal.
